//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class award
    {
        public int id { get; set; }
        public string name { get; set; }
        public string organization { get; set; }
        public Nullable<System.DateTime> date_deadline { get; set; }
        public Nullable<System.DateTime> date_announced { get; set; }
        public string website { get; set; }
        public string notes { get; set; }
        public string addressline1 { get; set; }
        public string addressline2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdat { get; set; }
        public int updatedby { get; set; }
        public System.DateTime updatedat { get; set; }
    }
}
