//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public contact()
        {
            this.contact_title = new HashSet<title>();
        }
    
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string website { get; set; }
        public string email1 { get; set; }
        public bool is_email1_primary { get; set; }
        public string email2 { get; set; }
        public bool is_email2_primary { get; set; }
        public string notes { get; set; }
        public string phone { get; set; }
        public bool is_subscriber { get; set; }
        public Nullable<System.DateTime> sub_startdate { get; set; }
        public Nullable<System.DateTime> sub_enddate { get; set; }
        public Nullable<int> sub_number { get; set; }
        public bool galley_all { get; set; }
        public bool galley_pos { get; set; }
        public Nullable<int> galley_copies { get; set; }
        public bool review_all { get; set; }
        public bool review_pos { get; set; }
        public Nullable<int> review_copies { get; set; }
        public bool desk_all { get; set; }
        public bool desk_pos { get; set; }
        public Nullable<int> desk_copies { get; set; }
        public bool comp_all { get; set; }
        public bool comp_pos { get; set; }
        public Nullable<int> comp_copies { get; set; }
        public string addressline1 { get; set; }
        public string addressline2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string title { get; set; }
        public string organization { get; set; }
        public bool is_primary { get; set; }
        public bool is_bad { get; set; }
        public string addressline1_alt { get; set; }
        public string addressline2_alt { get; set; }
        public string city_alt { get; set; }
        public string state_alt { get; set; }
        public string zip_alt { get; set; }
        public string country_alt { get; set; }
        public string organization_alt { get; set; }
        public string title_alt { get; set; }
        public bool is_primary_alt { get; set; }
        public bool is_bad_alt { get; set; }
        public string sub_type { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdat { get; set; }
        public int updatedby { get; set; }
        public System.DateTime updatedat { get; set; }

        public virtual ICollection<title> contact_title { get; set; }
        public virtual ICollection<review> contact_review { get; set; }
        public virtual ICollection<shipment> contact_shipment { get; set; }
        public virtual ICollection<contact_to_category> contact_contact_category { get; set; }
        public virtual user contact_user { get; set; }

    }
}
