//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment_to_award
    {
        public int shipment_id { get; set; }
        public int award_id { get; set; }
    }
}
