//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class title
    {
        public int id { get; set; }
        public string title1 { get; set; }
        public string subtitle { get; set; }
        public int author { get; set; }
        public string edition { get; set; }
        public string isbn { get; set; }
        public System.DateTime date_published { get; set; }
        public string notes { get; set; }
        public int createdby { get; set; }
        public System.DateTime createdat { get; set; }
        public int updatedby { get; set; }
        public System.DateTime updatedat { get; set; }
    
        public virtual contact author_contact { get; set; }
    }
}
