//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public bool is_admin { get; set; }
        public bool is_deleted { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updatedat { get; set; }
    }
}
