//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wavepoetry2Entities1 : DbContext
    {
        public wavepoetry2Entities1()
            : base("name=wavepoetry2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<award> awards { get; set; }
        public DbSet<award_categories> award_categories { get; set; }
        public DbSet<award_to_category> award_to_category { get; set; }
        public DbSet<award_to_contact> award_to_contact { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<contact_categories> contact_categories { get; set; }
        public DbSet<contact_to_category> contact_to_category { get; set; }
        public DbSet<review> reviews { get; set; }
        public DbSet<shipment> shipments { get; set; }
        public DbSet<shipment_to_award> shipment_to_award { get; set; }
        public DbSet<title> titles { get; set; }
        public DbSet<title_to_review> title_to_review { get; set; }
        public DbSet<user> users { get; set; }
    }
}
