//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class admevent
    {
        public int id { get; set; }
        public string @event { get; set; }
        public string location { get; set; }
        public string citystate { get; set; }
        public Nullable<System.DateTime> event_at { get; set; }
        public string heading { get; set; }
    }
}
