//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class author
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string bio { get; set; }
        public string aphoto { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public System.DateTime modified_at { get; set; }
        public string modified_by { get; set; }
        public string permalink { get; set; }
    }
}
