//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class bedazzler
    {
        public int id { get; set; }
        public string av_content { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> date_on { get; set; }
        public string bgcolor { get; set; }
        public string visible { get; set; }
    }
}
