//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class bedazzlet
    {
        public int id { get; set; }
        public int bedazzler_id { get; set; }
        public string lets_body { get; set; }
        public string lets_title { get; set; }
    }
}
