//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string jtitle { get; set; }
        public string organization { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string address4 { get; set; }
        public string city { get; set; }
        public string city2 { get; set; }
        public string state { get; set; }
        public string state2 { get; set; }
        public string zip { get; set; }
        public string zip2 { get; set; }
        public string country { get; set; }
        public string country2 { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public string badaddress { get; set; }
        public string bademail { get; set; }
        public string category { get; set; }
        public string salesrep { get; set; }
        public string saleskitsq { get; set; }
        public string extracovers { get; set; }
        public Nullable<System.DateTime> substart { get; set; }
        public Nullable<System.DateTime> subend { get; set; }
        public string subtype { get; set; }
        public string prizename { get; set; }
        public Nullable<System.DateTime> prizedeadline { get; set; }
        public string guidenote { get; set; }
        public string guidewebaddress { get; set; }
        public string followupmark { get; set; }
        public Nullable<System.DateTime> followup { get; set; }
        public string emaillist { get; set; }
        public string unsubscribed { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public System.DateTime modified_at { get; set; }
        public string modified_by { get; set; }
        public string always_gal { get; set; }
        public string always_galn { get; set; }
        public string poss_gal { get; set; }
        public string poss_galn { get; set; }
        public string always_rev { get; set; }
        public string always_revn { get; set; }
        public string poss_rev { get; set; }
        public string poss_revn { get; set; }
        public string always_comp { get; set; }
        public string always_compn { get; set; }
        public string poss_comp { get; set; }
        public string poss_compn { get; set; }
        public string unsubscribed2 { get; set; }
        public string cats_always { get; set; }
        public string dontsolicit { get; set; }
        public string sub_number { get; set; }
    }
}
