//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactfinal
    {
        public int id { get; set; }
        public int contact_id { get; set; }
        public int title_id { get; set; }
        public string contactfinal1 { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
    }
}
