//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineitem
    {
        public int id { get; set; }
        public int bounding_id { get; set; }
        public int title_id { get; set; }
        public int waveorder_id { get; set; }
        public int quantity { get; set; }
        public decimal unit_price { get; set; }
        public string status { get; set; }
    }
}
