//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int id { get; set; }
        public int title_id { get; set; }
        public string rev { get; set; }
        public string link { get; set; }
        public Nullable<System.DateTime> dated_on { get; set; }
        public string author { get; set; }
    }
}
