//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class special
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string special_text { get; set; }
        public string special_image { get; set; }
        public string special_caption { get; set; }
        public string special_title { get; set; }
        public string av_content { get; set; }
        public string link { get; set; }
        public Nullable<int> sorder { get; set; }
        public string editable { get; set; }
        public string visible { get; set; }
        public string visible_home { get; set; }
        public Nullable<int> horder { get; set; }
        public string delete_able { get; set; }
    }
}
