//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxship
    {
        public int id { get; set; }
        public Nullable<float> general_tax { get; set; }
        public Nullable<float> mass_tax { get; set; }
        public Nullable<float> wash_tax { get; set; }
        public Nullable<float> media_ship { get; set; }
        public Nullable<float> priority_ship { get; set; }
        public Nullable<float> canada_ship { get; set; }
        public Nullable<float> intern_ship { get; set; }
        public System.DateTime modified_at { get; set; }
        public string modified_by { get; set; }
    }
}
