//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class titleresource
    {
        public int id { get; set; }
        public int title_id { get; set; }
        public string av_desc { get; set; }
        public string av_content { get; set; }
        public string @public { get; set; }
        public Nullable<System.DateTime> resdate { get; set; }
        public string restext { get; set; }
    }
}
