//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class title
    {
        public int id { get; set; }
        public string title_status { get; set; }
        public string title1 { get; set; }
        public string subtitle_series { get; set; }
        public Nullable<int> pages { get; set; }
        public string headline { get; set; }
        public string description { get; set; }
        public string author_bio { get; set; }
        public string category { get; set; }
        public string sample_content { get; set; }
        public string awards { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public System.DateTime modified_at { get; set; }
        public string modified_by { get; set; }
        public string cover { get; set; }
        public string permalink { get; set; }
    }
}
