//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePoetry.OldDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class waveorder
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string stype { get; set; }
        public string sfname { get; set; }
        public string slname { get; set; }
        public string saddress { get; set; }
        public string saddress2 { get; set; }
        public string scity { get; set; }
        public string sstate { get; set; }
        public string szip { get; set; }
        public string scountry { get; set; }
        public string email { get; set; }
        public string pay_type { get; set; }
        public string cc_number { get; set; }
        public System.DateTime exp_on { get; set; }
        public Nullable<System.DateTime> ordered_at { get; set; }
        public string total { get; set; }
        public string tax { get; set; }
        public string notes { get; set; }
        public string coupon_codes { get; set; }
    }
}
